[2025-02-22T20:31:05.022+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_comic_fetcher.save_comic scheduled__2025-02-19T05:00:00+00:00 [queued]>
[2025-02-22T20:31:05.026+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_comic_fetcher.save_comic scheduled__2025-02-19T05:00:00+00:00 [queued]>
[2025-02-22T20:31:05.026+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-02-22T20:31:05.031+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): save_comic> on 2025-02-19 05:00:00+00:00
[2025-02-22T20:31:05.033+0000] {standard_task_runner.py:57} INFO - Started process 275 to run task
[2025-02-22T20:31:05.034+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xkcd_comic_fetcher', 'save_comic', 'scheduled__2025-02-19T05:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/xkcd-comics-dag.py', '--cfg-path', '/tmp/tmpe0t0m_27']
[2025-02-22T20:31:05.036+0000] {standard_task_runner.py:85} INFO - Job 62: Subtask save_comic
[2025-02-22T20:31:05.054+0000] {task_command.py:415} INFO - Running <TaskInstance: xkcd_comic_fetcher.save_comic scheduled__2025-02-19T05:00:00+00:00 [running]> on host 25ffd23c4844
[2025-02-22T20:31:05.081+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_comic_fetcher' AIRFLOW_CTX_TASK_ID='save_comic' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T05:00:00+00:00'
[2025-02-22T20:31:05.084+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-02-22T20:31:05.085+0000] {base.py:73} INFO - Using connection ID 'xkcd_db' for task execution.
[2025-02-22T20:31:05.086+0000] {sql.py:418} INFO - Running statement: 
        INSERT INTO comics 
        (comic_id, title, image_url, alt_text, publish_date, transcript, updated_at)
        VALUES (%s, %s, %s, %s, %s, %s, CURRENT_TIMESTAMP)
        ON CONFLICT (comic_id) 
        DO UPDATE SET 
            title = EXCLUDED.title,
            image_url = EXCLUDED.image_url,
            alt_text = EXCLUDED.alt_text,
            publish_date = EXCLUDED.publish_date,
            transcript = EXCLUDED.transcript,
            updated_at = CURRENT_TIMESTAMP;
    , parameters: (3054, 'Scream Cipher', 'https://imgs.xkcd.com/comics/scream_cipher.png', 'AAAAAA A ÃA̧AȂA̦ ǍÅÂÃĀÁȂ AAAAAAA!', '2025-2-21', '')
[2025-02-22T20:31:05.086+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/xkcd-comics-dag.py", line 76, in save_comic
    pg_hook.run(insert_sql, parameters=values)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 421, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UndefinedColumn: column "image_url" of relation "comics" does not exist
LINE 3:         (comic_id, title, image_url, alt_text, publish_date,...
                                  ^

[2025-02-22T20:31:05.089+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=xkcd_comic_fetcher, task_id=save_comic, execution_date=20250219T050000, start_date=20250222T203105, end_date=20250222T203105
[2025-02-22T20:31:05.093+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 62 for task save_comic (column "image_url" of relation "comics" does not exist
LINE 3:         (comic_id, title, image_url, alt_text, publish_date,...
                                  ^
; 275)
[2025-02-22T20:31:05.138+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-22T20:31:05.146+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
