[2025-03-03T05:13:05.134+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_comic_fetcher.wait_for_comic scheduled__2025-02-28T05:00:00+00:00 [queued]>
[2025-03-03T05:13:05.138+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_comic_fetcher.wait_for_comic scheduled__2025-02-28T05:00:00+00:00 [queued]>
[2025-03-03T05:13:05.138+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-03T05:13:05.143+0000] {taskinstance.py:1380} INFO - Executing <Task(XKCDComicSensor): wait_for_comic> on 2025-02-28 05:00:00+00:00
[2025-03-03T05:13:05.145+0000] {standard_task_runner.py:57} INFO - Started process 21475 to run task
[2025-03-03T05:13:05.147+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xkcd_comic_fetcher', 'wait_for_comic', 'scheduled__2025-02-28T05:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/xkcd-comics-dag.py', '--cfg-path', '/tmp/tmpxzrkd22p']
[2025-03-03T05:13:05.148+0000] {standard_task_runner.py:85} INFO - Job 77: Subtask wait_for_comic
[2025-03-03T05:13:05.166+0000] {task_command.py:415} INFO - Running <TaskInstance: xkcd_comic_fetcher.wait_for_comic scheduled__2025-02-28T05:00:00+00:00 [running]> on host 25ffd23c4844
[2025-03-03T05:13:05.196+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_comic_fetcher' AIRFLOW_CTX_TASK_ID='wait_for_comic' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-28T05:00:00+00:00'
[2025-03-03T05:13:05.197+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-03T05:13:05.197+0000] {base.py:73} INFO - Using connection ID 'xkcd_db' for task execution.
[2025-03-03T05:13:05.198+0000] {sql.py:418} INFO - Running statement: SELECT MAX(comic_id) FROM public.comics, parameters: None
[2025-03-03T05:13:05.199+0000] {sql.py:427} INFO - Rows affected: 1
[2025-03-03T05:13:05.204+0000] {xkcd_sensor.py:65} ERROR - Error checking for new comic: HTTPSConnectionPool(host='xkcd.com', port=443): Max retries exceeded with url: /info.0.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffb3865af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-03-03T06:26:55.278+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2025-03-03T06:26:55.281+0000] {process_utils.py:131} INFO - Sending 15 to group 21475. PIDs of all processes in the group: [21475]
[2025-03-03T06:26:55.281+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 21475
[2025-03-03T06:26:55.281+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-03T06:26:55.289+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/sensors/base.py", line 285, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-03-03T06:26:55.292+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=xkcd_comic_fetcher, task_id=wait_for_comic, execution_date=20250228T050000, start_date=20250303T051305, end_date=20250303T062655
[2025-03-03T06:26:55.300+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 77 for task wait_for_comic (Task received SIGTERM signal; 21475)
[2025-03-03T06:26:55.304+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=21475, status='terminated', exitcode=1, started='05:13:05') (21475) terminated with exit code 1
