[2025-03-03T12:39:22.232+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_dbt_transformations.dbt_debug manual__2025-03-03T12:39:20.767843+00:00 [queued]>
[2025-03-03T12:39:22.235+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_dbt_transformations.dbt_debug manual__2025-03-03T12:39:20.767843+00:00 [queued]>
[2025-03-03T12:39:22.236+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-03T12:39:22.241+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_debug> on 2025-03-03 12:39:20.767843+00:00
[2025-03-03T12:39:22.243+0000] {standard_task_runner.py:57} INFO - Started process 192 to run task
[2025-03-03T12:39:22.244+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xkcd_dbt_transformations', 'dbt_debug', 'manual__2025-03-03T12:39:20.767843+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/xkcd_dbt_transformations.py', '--cfg-path', '/tmp/tmpw16p3g56']
[2025-03-03T12:39:22.246+0000] {standard_task_runner.py:85} INFO - Job 89: Subtask dbt_debug
[2025-03-03T12:39:22.263+0000] {task_command.py:415} INFO - Running <TaskInstance: xkcd_dbt_transformations.dbt_debug manual__2025-03-03T12:39:20.767843+00:00 [running]> on host 9a8b57a0aa30
[2025-03-03T12:39:22.293+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_dbt_transformations' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T12:39:20.767843+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T12:39:20.767843+00:00'
[2025-03-03T12:39:22.294+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-03T12:39:22.294+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/dbt && python -m dbt.cli debug --no-use-colors']
[2025-03-03T12:39:22.298+0000] {subprocess.py:86} INFO - Output:
[2025-03-03T12:39:23.808+0000] {subprocess.py:93} INFO - : No module named dbt.cli.__main__; 'dbt.cli' is a package and cannot be directly executed
[2025-03-03T12:39:23.906+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-03T12:39:23.912+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-03T12:39:23.913+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=xkcd_dbt_transformations, task_id=dbt_debug, execution_date=20250303T123920, start_date=20250303T123922, end_date=20250303T123923
[2025-03-03T12:39:23.919+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 89 for task dbt_debug (Bash command failed. The command returned a non-zero exit code 1.; 192)
[2025-03-03T12:39:23.961+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-03T12:39:23.974+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
