[2025-02-22T19:40:31.662+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xkcd_comic_fetcher.setup_table scheduled__2025-02-19T05:00:00+00:00 [queued]>
[2025-02-22T19:40:31.669+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xkcd_comic_fetcher.setup_table scheduled__2025-02-19T05:00:00+00:00 [queued]>
[2025-02-22T19:40:31.670+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-02-22T19:40:31.677+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): setup_table> on 2025-02-19 05:00:00+00:00
[2025-02-22T19:40:31.679+0000] {standard_task_runner.py:57} INFO - Started process 189 to run task
[2025-02-22T19:40:31.682+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'xkcd_comic_fetcher', 'setup_table', 'scheduled__2025-02-19T05:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/xkcd-comics-dag.py', '--cfg-path', '/tmp/tmp_nfyt18z']
[2025-02-22T19:40:31.684+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask setup_table
[2025-02-22T19:40:31.715+0000] {task_command.py:415} INFO - Running <TaskInstance: xkcd_comic_fetcher.setup_table scheduled__2025-02-19T05:00:00+00:00 [running]> on host bcfb9908ca6b
[2025-02-22T19:40:31.753+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xkcd_comic_fetcher' AIRFLOW_CTX_TASK_ID='setup_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T05:00:00+00:00'
[2025-02-22T19:40:31.756+0000] {sql.py:274} INFO - Executing: 
CREATE TABLE IF NOT EXISTS comics (
    comic_id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    image_url TEXT NOT NULL,
    alt_text TEXT,
    publish_date DATE NOT NULL,
    transcript TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
[2025-02-22T19:40:31.783+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `xkcd_db` isn't defined
[2025-02-22T19:40:31.790+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=xkcd_comic_fetcher, task_id=setup_table, execution_date=20250219T050000, start_date=20250222T194031, end_date=20250222T194031
[2025-02-22T19:40:31.817+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 48 for task setup_table (The conn_id `xkcd_db` isn't defined; 189)
[2025-02-22T19:40:31.862+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-22T19:40:31.876+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
